version: "3.8"
services: 
    app:
        container_name: app-php
        build: 
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes: 
            - ./:/var/www
        networks: 
            - app-network

    nginx:
        image: nginx:alpine
        container_name: app-nginx
        restart: unless-stopped
        ports: 
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks: 
            - app-network

networks: 
    app-network:
        driver: bridge
